# Generated by Django 5.0.4 on 2024-05-21 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_product_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
