# Generated by Django 5.0.4 on 2024-04-22 09:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquetsize',
            name='flowers_required',
        ),
        migrations.RemoveField(
            model_name='bouquetsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.AddField(
            model_name='addon',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='addon',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='addon',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='BouquetFlowerRequirement',
        ),
        migrations.DeleteModel(
            name='Flower',
        ),
        migrations.DeleteModel(
            name='BouquetSize',
        ),
    ]
