# Generated by Django 5.0.4 on 2024-05-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_delete_addoninventory'),
        ('products', '0003_remove_bouquetsize_flowers_required_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddOn',
        ),
    ]
