# Generated by Django 5.0.4 on 2024-05-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_addon',
            field=models.BooleanField(default=False),
        ),
    ]
